stages: [build, test]

build_job:
  stage: build
  script:
    - chmod +x ./sample-app.sh || true
    - bash ./sample-app.sh

test_job:
  stage: test
  script:
    - curl "http://localhost:5050/" | grep "You are calling me from"